version: "3.8"

services:
    app:
        build:
            context: .
        environment:
            # On passe l'URL de la BDD de test à l'application
            - APP_ENV=test
            - TEST_DATABASE_URL=mysql://testuser:testpass@db:3306/testdb?serverVersion=mariadb-11.4

    db:
        image: mariadb:11.4
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=testdb
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpass
        volumes:
            - ./db_data:/var/lib/mysql
